export const allBanksInNigeria = [
  "Access Bank Plc",
  "Accion Microfinance Bank",
  "Citibank Nigeria Limited",
  "Ecobank Nigeria",
  "Fidelity Bank Plc",
  "Finca Microfinance Bank Limited",
  "Fina Trust Microfinance Bank",
  "First City Monument Bank Limited",
  "First Bank of Nigeria Limited",
  "Guaranty Trust Bank Plc",
  "Globus Bank Limited",
  "Heritage Bank Plc",
  "Infinity Microfinance Bank",
  "Jaiz Bank Plc",
  "Keystone Bank Limited",
  "Kuda Bank",
  "Mutual Trust Microfinance Bank",
  "Peace Microfinance Bank",
  "Pearl Microfinance Bank Limited",
  "Polaris Bank Limited",
  "Providus Bank Limited",
  "Sparkle Bank",
  "Stanbic IBTC Bank Plc",
  "Standard Chartered",
  "Sterling Bank Plc",
  "SunTrust Bank Nigeria Limited",
  "TAJBank Limited",
  "Titan Trust Bank Limited",
  "Union Bank of Nigeria Plc",
  "United Bank for Africa Plc",
  "Unity Bank Plc",
  "Wema Bank Plc",
  "Zenith Bank Plc",
];

export const allBusinessTypes = [
  "Sole proprietorship",
  "Partnership",
  "LLP",
  "LLC",
  "Series LLC",
  "C corporation",
  "S corporation",
  "Nonprofit corporation",
  "Benefit corporation",
  "L3C",
];

export const allBusinessCategories = [
  "E-tailer",
  "Independent/COOP/Natural Product",
  "Chain Natural Products Store",
  "Gourmet/Specialty Products",
  "Personal Care",
  "Independent Grocer",
  "Conventional Supermarket",
  "Discount/Mass Merchandiser",
  "Chain Drug Store/Pharmacy",
  "Gift/Bookstore",
  "Independent Drug Store/Pharmacy",
  "Mail Order Catalog",
  "Home and Textile",
  "Convenience Store",
  "Pet Supply Store/Grooming",
];
